Relocated mod methods to API
iron431/Irons-Spells-n-Spellbooks pull request #405
Opened 2024-04-21 13:21 UTC by IGN-Styly

Relocates base methods to the API for addon use.

### Contributor Liscence Agreement
[Full CLA](https://github.com/iron431/Irons-Spells-n-Spellbooks/blob/1.19.2/CLA.md)
*Contributors: Please "X" in the following box to acknowledge our CLA*
- [X] I have read and agree to the CLA for Iron's Spells and Spellbooks which allows me to retain my ownership in the code submitted while granting the repository owner legal rights to use my contribution.

2024-04-21 13:23 UTC, IGN-Styly commented
Also removes need for the UpdateClient utility class, by sending the mana update event via Messages.

2024-04-21 15:14 UTC, iron431 requested changes
also this is in the wrong branch, 1.19.2 is the development branch; 1.20.1 should not be worked on directly

2024-04-21 15:14 UTC, iron431 commented on src/main/java/io/redspace/ironsspellbooks/api/magic/MagicData.java
none of these changes on magic data should be made

2024-04-21 19:21 UTC, iron431 commented on src/main/java/io/redspace/ironsspellbooks/api/magic/MagicData.java
to explain better, sending the packet bypasses optimization made to reduce network traffic, and there seem to be erroneous imports added to the file

2024-04-27 09:01 UTC, IGN-Styly commented
sent to wrong repo my bad

2024-04-27 09:01 UTC, closed without merging